### ISSUE TITLE
TypeError: this.emit is not a function

### ISSUE THREAD

**Issue by Tehren** [A-312/gulp-terser-js#4]
When the plugin encounters an error in my javascript code, it logs the error, but this is followed by a TypeError that breaks my gulp watch script.

It seems that the "this" context in the printError function no longers refers to the gulp stream.

Platform: Windows
Error:
D:\..\node_modules\gulp-terser-js\index.js:82
        return this.emit('end');
                    ^

TypeError: this.emit is not a function
    at printError (D:\..\node_modules\gulp-terser-js\index.js:82:14)
    at DestroyableTransform._transform (D:\..\node_modules\gulp-terser-js\index.js:40:7)
    at DestroyableTransform.Transform._read (D:\..\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (D:\..\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (D:\..\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (D:\..\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (D:\..\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DestroyableTransform.ondata (D:\..\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:182:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:459:23)

**Comment by A-312** [comment]
I am making a fix

**Comment by A-312** [comment]
Done :)

@Tehren Thanks for this report ! :)
